################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (13.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../Middlewares/wolfssl/wolfcrypt/src/aes.c \
../Middlewares/wolfssl/wolfcrypt/src/arc4.c \
../Middlewares/wolfssl/wolfcrypt/src/ascon.c \
../Middlewares/wolfssl/wolfcrypt/src/asm.c \
../Middlewares/wolfssl/wolfcrypt/src/asn.c \
../Middlewares/wolfssl/wolfcrypt/src/async.c \
../Middlewares/wolfssl/wolfcrypt/src/blake2b.c \
../Middlewares/wolfssl/wolfcrypt/src/blake2s.c \
../Middlewares/wolfssl/wolfcrypt/src/camellia.c \
../Middlewares/wolfssl/wolfcrypt/src/chacha.c \
../Middlewares/wolfssl/wolfcrypt/src/chacha20_poly1305.c \
../Middlewares/wolfssl/wolfcrypt/src/cmac.c \
../Middlewares/wolfssl/wolfcrypt/src/coding.c \
../Middlewares/wolfssl/wolfcrypt/src/compress.c \
../Middlewares/wolfssl/wolfcrypt/src/cpuid.c \
../Middlewares/wolfssl/wolfcrypt/src/cryptocb.c \
../Middlewares/wolfssl/wolfcrypt/src/curve25519.c \
../Middlewares/wolfssl/wolfcrypt/src/curve448.c \
../Middlewares/wolfssl/wolfcrypt/src/des3.c \
../Middlewares/wolfssl/wolfcrypt/src/dh.c \
../Middlewares/wolfssl/wolfcrypt/src/dilithium.c \
../Middlewares/wolfssl/wolfcrypt/src/dsa.c \
../Middlewares/wolfssl/wolfcrypt/src/ecc.c \
../Middlewares/wolfssl/wolfcrypt/src/ecc_fp.c \
../Middlewares/wolfssl/wolfcrypt/src/eccsi.c \
../Middlewares/wolfssl/wolfcrypt/src/ed25519.c \
../Middlewares/wolfssl/wolfcrypt/src/ed448.c \
../Middlewares/wolfssl/wolfcrypt/src/error.c \
../Middlewares/wolfssl/wolfcrypt/src/evp.c \
../Middlewares/wolfssl/wolfcrypt/src/ext_lms.c \
../Middlewares/wolfssl/wolfcrypt/src/ext_mlkem.c \
../Middlewares/wolfssl/wolfcrypt/src/ext_xmss.c \
../Middlewares/wolfssl/wolfcrypt/src/falcon.c \
../Middlewares/wolfssl/wolfcrypt/src/fe_448.c \
../Middlewares/wolfssl/wolfcrypt/src/fe_low_mem.c \
../Middlewares/wolfssl/wolfcrypt/src/fe_operations.c \
../Middlewares/wolfssl/wolfcrypt/src/fips.c \
../Middlewares/wolfssl/wolfcrypt/src/fips_test.c \
../Middlewares/wolfssl/wolfcrypt/src/ge_448.c \
../Middlewares/wolfssl/wolfcrypt/src/ge_low_mem.c \
../Middlewares/wolfssl/wolfcrypt/src/ge_operations.c \
../Middlewares/wolfssl/wolfcrypt/src/hash.c \
../Middlewares/wolfssl/wolfcrypt/src/hmac.c \
../Middlewares/wolfssl/wolfcrypt/src/hpke.c \
../Middlewares/wolfssl/wolfcrypt/src/integer.c \
../Middlewares/wolfssl/wolfcrypt/src/kdf.c \
../Middlewares/wolfssl/wolfcrypt/src/logging.c \
../Middlewares/wolfssl/wolfcrypt/src/md2.c \
../Middlewares/wolfssl/wolfcrypt/src/md4.c \
../Middlewares/wolfssl/wolfcrypt/src/md5.c \
../Middlewares/wolfssl/wolfcrypt/src/memory.c \
../Middlewares/wolfssl/wolfcrypt/src/misc.c \
../Middlewares/wolfssl/wolfcrypt/src/pkcs12.c \
../Middlewares/wolfssl/wolfcrypt/src/pkcs7.c \
../Middlewares/wolfssl/wolfcrypt/src/poly1305.c \
../Middlewares/wolfssl/wolfcrypt/src/pwdbased.c \
../Middlewares/wolfssl/wolfcrypt/src/random.c \
../Middlewares/wolfssl/wolfcrypt/src/rc2.c \
../Middlewares/wolfssl/wolfcrypt/src/ripemd.c \
../Middlewares/wolfssl/wolfcrypt/src/rsa.c \
../Middlewares/wolfssl/wolfcrypt/src/sakke.c \
../Middlewares/wolfssl/wolfcrypt/src/selftest.c \
../Middlewares/wolfssl/wolfcrypt/src/sha.c \
../Middlewares/wolfssl/wolfcrypt/src/sha256.c \
../Middlewares/wolfssl/wolfcrypt/src/sha3.c \
../Middlewares/wolfssl/wolfcrypt/src/sha512.c \
../Middlewares/wolfssl/wolfcrypt/src/signature.c \
../Middlewares/wolfssl/wolfcrypt/src/siphash.c \
../Middlewares/wolfssl/wolfcrypt/src/sm2.c \
../Middlewares/wolfssl/wolfcrypt/src/sm3.c \
../Middlewares/wolfssl/wolfcrypt/src/sm4.c \
../Middlewares/wolfssl/wolfcrypt/src/sp_arm32.c \
../Middlewares/wolfssl/wolfcrypt/src/sp_arm64.c \
../Middlewares/wolfssl/wolfcrypt/src/sp_armthumb.c \
../Middlewares/wolfssl/wolfcrypt/src/sp_c32.c \
../Middlewares/wolfssl/wolfcrypt/src/sp_c64.c \
../Middlewares/wolfssl/wolfcrypt/src/sp_cortexm.c \
../Middlewares/wolfssl/wolfcrypt/src/sp_dsp32.c \
../Middlewares/wolfssl/wolfcrypt/src/sp_int.c \
../Middlewares/wolfssl/wolfcrypt/src/sp_sm2_arm32.c \
../Middlewares/wolfssl/wolfcrypt/src/sp_sm2_arm64.c \
../Middlewares/wolfssl/wolfcrypt/src/sp_sm2_armthumb.c \
../Middlewares/wolfssl/wolfcrypt/src/sp_sm2_c32.c \
../Middlewares/wolfssl/wolfcrypt/src/sp_sm2_c64.c \
../Middlewares/wolfssl/wolfcrypt/src/sp_sm2_cortexm.c \
../Middlewares/wolfssl/wolfcrypt/src/sp_sm2_x86_64.c \
../Middlewares/wolfssl/wolfcrypt/src/sp_x86_64.c \
../Middlewares/wolfssl/wolfcrypt/src/sphincs.c \
../Middlewares/wolfssl/wolfcrypt/src/srp.c \
../Middlewares/wolfssl/wolfcrypt/src/tfm.c \
../Middlewares/wolfssl/wolfcrypt/src/wc_dsp.c \
../Middlewares/wolfssl/wolfcrypt/src/wc_encrypt.c \
../Middlewares/wolfssl/wolfcrypt/src/wc_lms.c \
../Middlewares/wolfssl/wolfcrypt/src/wc_lms_impl.c \
../Middlewares/wolfssl/wolfcrypt/src/wc_mlkem.c \
../Middlewares/wolfssl/wolfcrypt/src/wc_mlkem_poly.c \
../Middlewares/wolfssl/wolfcrypt/src/wc_pkcs11.c \
../Middlewares/wolfssl/wolfcrypt/src/wc_port.c \
../Middlewares/wolfssl/wolfcrypt/src/wc_xmss.c \
../Middlewares/wolfssl/wolfcrypt/src/wc_xmss_impl.c \
../Middlewares/wolfssl/wolfcrypt/src/wolfcrypt_first.c \
../Middlewares/wolfssl/wolfcrypt/src/wolfcrypt_last.c \
../Middlewares/wolfssl/wolfcrypt/src/wolfevent.c \
../Middlewares/wolfssl/wolfcrypt/src/wolfmath.c 

OBJS += \
./Middlewares/wolfssl/wolfcrypt/src/aes.o \
./Middlewares/wolfssl/wolfcrypt/src/arc4.o \
./Middlewares/wolfssl/wolfcrypt/src/ascon.o \
./Middlewares/wolfssl/wolfcrypt/src/asm.o \
./Middlewares/wolfssl/wolfcrypt/src/asn.o \
./Middlewares/wolfssl/wolfcrypt/src/async.o \
./Middlewares/wolfssl/wolfcrypt/src/blake2b.o \
./Middlewares/wolfssl/wolfcrypt/src/blake2s.o \
./Middlewares/wolfssl/wolfcrypt/src/camellia.o \
./Middlewares/wolfssl/wolfcrypt/src/chacha.o \
./Middlewares/wolfssl/wolfcrypt/src/chacha20_poly1305.o \
./Middlewares/wolfssl/wolfcrypt/src/cmac.o \
./Middlewares/wolfssl/wolfcrypt/src/coding.o \
./Middlewares/wolfssl/wolfcrypt/src/compress.o \
./Middlewares/wolfssl/wolfcrypt/src/cpuid.o \
./Middlewares/wolfssl/wolfcrypt/src/cryptocb.o \
./Middlewares/wolfssl/wolfcrypt/src/curve25519.o \
./Middlewares/wolfssl/wolfcrypt/src/curve448.o \
./Middlewares/wolfssl/wolfcrypt/src/des3.o \
./Middlewares/wolfssl/wolfcrypt/src/dh.o \
./Middlewares/wolfssl/wolfcrypt/src/dilithium.o \
./Middlewares/wolfssl/wolfcrypt/src/dsa.o \
./Middlewares/wolfssl/wolfcrypt/src/ecc.o \
./Middlewares/wolfssl/wolfcrypt/src/ecc_fp.o \
./Middlewares/wolfssl/wolfcrypt/src/eccsi.o \
./Middlewares/wolfssl/wolfcrypt/src/ed25519.o \
./Middlewares/wolfssl/wolfcrypt/src/ed448.o \
./Middlewares/wolfssl/wolfcrypt/src/error.o \
./Middlewares/wolfssl/wolfcrypt/src/evp.o \
./Middlewares/wolfssl/wolfcrypt/src/ext_lms.o \
./Middlewares/wolfssl/wolfcrypt/src/ext_mlkem.o \
./Middlewares/wolfssl/wolfcrypt/src/ext_xmss.o \
./Middlewares/wolfssl/wolfcrypt/src/falcon.o \
./Middlewares/wolfssl/wolfcrypt/src/fe_448.o \
./Middlewares/wolfssl/wolfcrypt/src/fe_low_mem.o \
./Middlewares/wolfssl/wolfcrypt/src/fe_operations.o \
./Middlewares/wolfssl/wolfcrypt/src/fips.o \
./Middlewares/wolfssl/wolfcrypt/src/fips_test.o \
./Middlewares/wolfssl/wolfcrypt/src/ge_448.o \
./Middlewares/wolfssl/wolfcrypt/src/ge_low_mem.o \
./Middlewares/wolfssl/wolfcrypt/src/ge_operations.o \
./Middlewares/wolfssl/wolfcrypt/src/hash.o \
./Middlewares/wolfssl/wolfcrypt/src/hmac.o \
./Middlewares/wolfssl/wolfcrypt/src/hpke.o \
./Middlewares/wolfssl/wolfcrypt/src/integer.o \
./Middlewares/wolfssl/wolfcrypt/src/kdf.o \
./Middlewares/wolfssl/wolfcrypt/src/logging.o \
./Middlewares/wolfssl/wolfcrypt/src/md2.o \
./Middlewares/wolfssl/wolfcrypt/src/md4.o \
./Middlewares/wolfssl/wolfcrypt/src/md5.o \
./Middlewares/wolfssl/wolfcrypt/src/memory.o \
./Middlewares/wolfssl/wolfcrypt/src/misc.o \
./Middlewares/wolfssl/wolfcrypt/src/pkcs12.o \
./Middlewares/wolfssl/wolfcrypt/src/pkcs7.o \
./Middlewares/wolfssl/wolfcrypt/src/poly1305.o \
./Middlewares/wolfssl/wolfcrypt/src/pwdbased.o \
./Middlewares/wolfssl/wolfcrypt/src/random.o \
./Middlewares/wolfssl/wolfcrypt/src/rc2.o \
./Middlewares/wolfssl/wolfcrypt/src/ripemd.o \
./Middlewares/wolfssl/wolfcrypt/src/rsa.o \
./Middlewares/wolfssl/wolfcrypt/src/sakke.o \
./Middlewares/wolfssl/wolfcrypt/src/selftest.o \
./Middlewares/wolfssl/wolfcrypt/src/sha.o \
./Middlewares/wolfssl/wolfcrypt/src/sha256.o \
./Middlewares/wolfssl/wolfcrypt/src/sha3.o \
./Middlewares/wolfssl/wolfcrypt/src/sha512.o \
./Middlewares/wolfssl/wolfcrypt/src/signature.o \
./Middlewares/wolfssl/wolfcrypt/src/siphash.o \
./Middlewares/wolfssl/wolfcrypt/src/sm2.o \
./Middlewares/wolfssl/wolfcrypt/src/sm3.o \
./Middlewares/wolfssl/wolfcrypt/src/sm4.o \
./Middlewares/wolfssl/wolfcrypt/src/sp_arm32.o \
./Middlewares/wolfssl/wolfcrypt/src/sp_arm64.o \
./Middlewares/wolfssl/wolfcrypt/src/sp_armthumb.o \
./Middlewares/wolfssl/wolfcrypt/src/sp_c32.o \
./Middlewares/wolfssl/wolfcrypt/src/sp_c64.o \
./Middlewares/wolfssl/wolfcrypt/src/sp_cortexm.o \
./Middlewares/wolfssl/wolfcrypt/src/sp_dsp32.o \
./Middlewares/wolfssl/wolfcrypt/src/sp_int.o \
./Middlewares/wolfssl/wolfcrypt/src/sp_sm2_arm32.o \
./Middlewares/wolfssl/wolfcrypt/src/sp_sm2_arm64.o \
./Middlewares/wolfssl/wolfcrypt/src/sp_sm2_armthumb.o \
./Middlewares/wolfssl/wolfcrypt/src/sp_sm2_c32.o \
./Middlewares/wolfssl/wolfcrypt/src/sp_sm2_c64.o \
./Middlewares/wolfssl/wolfcrypt/src/sp_sm2_cortexm.o \
./Middlewares/wolfssl/wolfcrypt/src/sp_sm2_x86_64.o \
./Middlewares/wolfssl/wolfcrypt/src/sp_x86_64.o \
./Middlewares/wolfssl/wolfcrypt/src/sphincs.o \
./Middlewares/wolfssl/wolfcrypt/src/srp.o \
./Middlewares/wolfssl/wolfcrypt/src/tfm.o \
./Middlewares/wolfssl/wolfcrypt/src/wc_dsp.o \
./Middlewares/wolfssl/wolfcrypt/src/wc_encrypt.o \
./Middlewares/wolfssl/wolfcrypt/src/wc_lms.o \
./Middlewares/wolfssl/wolfcrypt/src/wc_lms_impl.o \
./Middlewares/wolfssl/wolfcrypt/src/wc_mlkem.o \
./Middlewares/wolfssl/wolfcrypt/src/wc_mlkem_poly.o \
./Middlewares/wolfssl/wolfcrypt/src/wc_pkcs11.o \
./Middlewares/wolfssl/wolfcrypt/src/wc_port.o \
./Middlewares/wolfssl/wolfcrypt/src/wc_xmss.o \
./Middlewares/wolfssl/wolfcrypt/src/wc_xmss_impl.o \
./Middlewares/wolfssl/wolfcrypt/src/wolfcrypt_first.o \
./Middlewares/wolfssl/wolfcrypt/src/wolfcrypt_last.o \
./Middlewares/wolfssl/wolfcrypt/src/wolfevent.o \
./Middlewares/wolfssl/wolfcrypt/src/wolfmath.o 

C_DEPS += \
./Middlewares/wolfssl/wolfcrypt/src/aes.d \
./Middlewares/wolfssl/wolfcrypt/src/arc4.d \
./Middlewares/wolfssl/wolfcrypt/src/ascon.d \
./Middlewares/wolfssl/wolfcrypt/src/asm.d \
./Middlewares/wolfssl/wolfcrypt/src/asn.d \
./Middlewares/wolfssl/wolfcrypt/src/async.d \
./Middlewares/wolfssl/wolfcrypt/src/blake2b.d \
./Middlewares/wolfssl/wolfcrypt/src/blake2s.d \
./Middlewares/wolfssl/wolfcrypt/src/camellia.d \
./Middlewares/wolfssl/wolfcrypt/src/chacha.d \
./Middlewares/wolfssl/wolfcrypt/src/chacha20_poly1305.d \
./Middlewares/wolfssl/wolfcrypt/src/cmac.d \
./Middlewares/wolfssl/wolfcrypt/src/coding.d \
./Middlewares/wolfssl/wolfcrypt/src/compress.d \
./Middlewares/wolfssl/wolfcrypt/src/cpuid.d \
./Middlewares/wolfssl/wolfcrypt/src/cryptocb.d \
./Middlewares/wolfssl/wolfcrypt/src/curve25519.d \
./Middlewares/wolfssl/wolfcrypt/src/curve448.d \
./Middlewares/wolfssl/wolfcrypt/src/des3.d \
./Middlewares/wolfssl/wolfcrypt/src/dh.d \
./Middlewares/wolfssl/wolfcrypt/src/dilithium.d \
./Middlewares/wolfssl/wolfcrypt/src/dsa.d \
./Middlewares/wolfssl/wolfcrypt/src/ecc.d \
./Middlewares/wolfssl/wolfcrypt/src/ecc_fp.d \
./Middlewares/wolfssl/wolfcrypt/src/eccsi.d \
./Middlewares/wolfssl/wolfcrypt/src/ed25519.d \
./Middlewares/wolfssl/wolfcrypt/src/ed448.d \
./Middlewares/wolfssl/wolfcrypt/src/error.d \
./Middlewares/wolfssl/wolfcrypt/src/evp.d \
./Middlewares/wolfssl/wolfcrypt/src/ext_lms.d \
./Middlewares/wolfssl/wolfcrypt/src/ext_mlkem.d \
./Middlewares/wolfssl/wolfcrypt/src/ext_xmss.d \
./Middlewares/wolfssl/wolfcrypt/src/falcon.d \
./Middlewares/wolfssl/wolfcrypt/src/fe_448.d \
./Middlewares/wolfssl/wolfcrypt/src/fe_low_mem.d \
./Middlewares/wolfssl/wolfcrypt/src/fe_operations.d \
./Middlewares/wolfssl/wolfcrypt/src/fips.d \
./Middlewares/wolfssl/wolfcrypt/src/fips_test.d \
./Middlewares/wolfssl/wolfcrypt/src/ge_448.d \
./Middlewares/wolfssl/wolfcrypt/src/ge_low_mem.d \
./Middlewares/wolfssl/wolfcrypt/src/ge_operations.d \
./Middlewares/wolfssl/wolfcrypt/src/hash.d \
./Middlewares/wolfssl/wolfcrypt/src/hmac.d \
./Middlewares/wolfssl/wolfcrypt/src/hpke.d \
./Middlewares/wolfssl/wolfcrypt/src/integer.d \
./Middlewares/wolfssl/wolfcrypt/src/kdf.d \
./Middlewares/wolfssl/wolfcrypt/src/logging.d \
./Middlewares/wolfssl/wolfcrypt/src/md2.d \
./Middlewares/wolfssl/wolfcrypt/src/md4.d \
./Middlewares/wolfssl/wolfcrypt/src/md5.d \
./Middlewares/wolfssl/wolfcrypt/src/memory.d \
./Middlewares/wolfssl/wolfcrypt/src/misc.d \
./Middlewares/wolfssl/wolfcrypt/src/pkcs12.d \
./Middlewares/wolfssl/wolfcrypt/src/pkcs7.d \
./Middlewares/wolfssl/wolfcrypt/src/poly1305.d \
./Middlewares/wolfssl/wolfcrypt/src/pwdbased.d \
./Middlewares/wolfssl/wolfcrypt/src/random.d \
./Middlewares/wolfssl/wolfcrypt/src/rc2.d \
./Middlewares/wolfssl/wolfcrypt/src/ripemd.d \
./Middlewares/wolfssl/wolfcrypt/src/rsa.d \
./Middlewares/wolfssl/wolfcrypt/src/sakke.d \
./Middlewares/wolfssl/wolfcrypt/src/selftest.d \
./Middlewares/wolfssl/wolfcrypt/src/sha.d \
./Middlewares/wolfssl/wolfcrypt/src/sha256.d \
./Middlewares/wolfssl/wolfcrypt/src/sha3.d \
./Middlewares/wolfssl/wolfcrypt/src/sha512.d \
./Middlewares/wolfssl/wolfcrypt/src/signature.d \
./Middlewares/wolfssl/wolfcrypt/src/siphash.d \
./Middlewares/wolfssl/wolfcrypt/src/sm2.d \
./Middlewares/wolfssl/wolfcrypt/src/sm3.d \
./Middlewares/wolfssl/wolfcrypt/src/sm4.d \
./Middlewares/wolfssl/wolfcrypt/src/sp_arm32.d \
./Middlewares/wolfssl/wolfcrypt/src/sp_arm64.d \
./Middlewares/wolfssl/wolfcrypt/src/sp_armthumb.d \
./Middlewares/wolfssl/wolfcrypt/src/sp_c32.d \
./Middlewares/wolfssl/wolfcrypt/src/sp_c64.d \
./Middlewares/wolfssl/wolfcrypt/src/sp_cortexm.d \
./Middlewares/wolfssl/wolfcrypt/src/sp_dsp32.d \
./Middlewares/wolfssl/wolfcrypt/src/sp_int.d \
./Middlewares/wolfssl/wolfcrypt/src/sp_sm2_arm32.d \
./Middlewares/wolfssl/wolfcrypt/src/sp_sm2_arm64.d \
./Middlewares/wolfssl/wolfcrypt/src/sp_sm2_armthumb.d \
./Middlewares/wolfssl/wolfcrypt/src/sp_sm2_c32.d \
./Middlewares/wolfssl/wolfcrypt/src/sp_sm2_c64.d \
./Middlewares/wolfssl/wolfcrypt/src/sp_sm2_cortexm.d \
./Middlewares/wolfssl/wolfcrypt/src/sp_sm2_x86_64.d \
./Middlewares/wolfssl/wolfcrypt/src/sp_x86_64.d \
./Middlewares/wolfssl/wolfcrypt/src/sphincs.d \
./Middlewares/wolfssl/wolfcrypt/src/srp.d \
./Middlewares/wolfssl/wolfcrypt/src/tfm.d \
./Middlewares/wolfssl/wolfcrypt/src/wc_dsp.d \
./Middlewares/wolfssl/wolfcrypt/src/wc_encrypt.d \
./Middlewares/wolfssl/wolfcrypt/src/wc_lms.d \
./Middlewares/wolfssl/wolfcrypt/src/wc_lms_impl.d \
./Middlewares/wolfssl/wolfcrypt/src/wc_mlkem.d \
./Middlewares/wolfssl/wolfcrypt/src/wc_mlkem_poly.d \
./Middlewares/wolfssl/wolfcrypt/src/wc_pkcs11.d \
./Middlewares/wolfssl/wolfcrypt/src/wc_port.d \
./Middlewares/wolfssl/wolfcrypt/src/wc_xmss.d \
./Middlewares/wolfssl/wolfcrypt/src/wc_xmss_impl.d \
./Middlewares/wolfssl/wolfcrypt/src/wolfcrypt_first.d \
./Middlewares/wolfssl/wolfcrypt/src/wolfcrypt_last.d \
./Middlewares/wolfssl/wolfcrypt/src/wolfevent.d \
./Middlewares/wolfssl/wolfcrypt/src/wolfmath.d 


# Each subdirectory must supply rules for building sources it contributes
Middlewares/wolfssl/wolfcrypt/src/%.o Middlewares/wolfssl/wolfcrypt/src/%.su Middlewares/wolfssl/wolfcrypt/src/%.cyclo: ../Middlewares/wolfssl/wolfcrypt/src/%.c Middlewares/wolfssl/wolfcrypt/src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DDEBUG -DWOLFSSL_USER_SETTINGS -DNX_INCLUDE_USER_DEFINE_FILE -DUSE_HAL_DRIVER -DSTM32N657xx -DETH_PHY_1000MBITS_SUPPORTED -DNX_SECURE_INCLUDE_USER_DEFINE_FILE -DTX_SINGLE_MODE_SECURE=1 -DRTL8211_INIT_TO=10000 -DTX_INCLUDE_USER_DEFINE_FILE -c -I../../NetXDuo/App -I/home/mika/Schreibtisch/STM32CubeN6/Projects/STM32N6570-DK/Applications/NetXDuo/Nx_MQTT_Client/STM32CubeIDE/Middlewares/wolfssl -I../../NetXDuo/Target -I../../Core/Inc -I../../AZURE_RTOS/App -I../../../../../../../Middlewares/ST/netxduo/common/drivers/ethernet -I../../../../../../../Middlewares/ST/netxduo/nx_secure/inc -I../../../../../../../Middlewares/ST/netxduo/nx_secure/ports -I../../../../../../../Drivers/STM32N6xx_HAL_Driver/Inc -I../../../../../../../Middlewares/ST/netxduo/crypto_libraries/inc -I../../../../../../../Middlewares/ST/netxduo/tsn/inc -I../../../../../../../Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../../../../../Middlewares/ST/netxduo/addons/mqtt -I../../../../../../../Middlewares/ST/netxduo/addons/dhcp -I../../../../../../../Middlewares/ST/netxduo/addons/sntp -I../../../../../../../Middlewares/ST/netxduo/addons/dns -I../../../../../../../Middlewares/ST/threadx/common/inc -I../../../../../../../Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../../../../../Middlewares/ST/netxduo/common/inc -I../../../../../../../Middlewares/ST/netxduo/ports/cortex_m55/gnu/inc -I../../../../../../../Middlewares/ST/threadx/ports/cortex_m55/gnu/inc -I../../../../../../../Drivers/CMSIS/Include -I../../../../../../../Drivers/CMSIS/Device/ST/STM32N6xx/Include/Templates -I../../../../../../../Drivers/BSP/Components/rtl8211 -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-Middlewares-2f-wolfssl-2f-wolfcrypt-2f-src

clean-Middlewares-2f-wolfssl-2f-wolfcrypt-2f-src:
	-$(RM) ./Middlewares/wolfssl/wolfcrypt/src/aes.cyclo ./Middlewares/wolfssl/wolfcrypt/src/aes.d ./Middlewares/wolfssl/wolfcrypt/src/aes.o ./Middlewares/wolfssl/wolfcrypt/src/aes.su ./Middlewares/wolfssl/wolfcrypt/src/arc4.cyclo ./Middlewares/wolfssl/wolfcrypt/src/arc4.d ./Middlewares/wolfssl/wolfcrypt/src/arc4.o ./Middlewares/wolfssl/wolfcrypt/src/arc4.su ./Middlewares/wolfssl/wolfcrypt/src/ascon.cyclo ./Middlewares/wolfssl/wolfcrypt/src/ascon.d ./Middlewares/wolfssl/wolfcrypt/src/ascon.o ./Middlewares/wolfssl/wolfcrypt/src/ascon.su ./Middlewares/wolfssl/wolfcrypt/src/asm.cyclo ./Middlewares/wolfssl/wolfcrypt/src/asm.d ./Middlewares/wolfssl/wolfcrypt/src/asm.o ./Middlewares/wolfssl/wolfcrypt/src/asm.su ./Middlewares/wolfssl/wolfcrypt/src/asn.cyclo ./Middlewares/wolfssl/wolfcrypt/src/asn.d ./Middlewares/wolfssl/wolfcrypt/src/asn.o ./Middlewares/wolfssl/wolfcrypt/src/asn.su ./Middlewares/wolfssl/wolfcrypt/src/async.cyclo ./Middlewares/wolfssl/wolfcrypt/src/async.d ./Middlewares/wolfssl/wolfcrypt/src/async.o ./Middlewares/wolfssl/wolfcrypt/src/async.su ./Middlewares/wolfssl/wolfcrypt/src/blake2b.cyclo ./Middlewares/wolfssl/wolfcrypt/src/blake2b.d ./Middlewares/wolfssl/wolfcrypt/src/blake2b.o ./Middlewares/wolfssl/wolfcrypt/src/blake2b.su ./Middlewares/wolfssl/wolfcrypt/src/blake2s.cyclo ./Middlewares/wolfssl/wolfcrypt/src/blake2s.d ./Middlewares/wolfssl/wolfcrypt/src/blake2s.o ./Middlewares/wolfssl/wolfcrypt/src/blake2s.su ./Middlewares/wolfssl/wolfcrypt/src/camellia.cyclo ./Middlewares/wolfssl/wolfcrypt/src/camellia.d ./Middlewares/wolfssl/wolfcrypt/src/camellia.o ./Middlewares/wolfssl/wolfcrypt/src/camellia.su ./Middlewares/wolfssl/wolfcrypt/src/chacha.cyclo ./Middlewares/wolfssl/wolfcrypt/src/chacha.d ./Middlewares/wolfssl/wolfcrypt/src/chacha.o ./Middlewares/wolfssl/wolfcrypt/src/chacha.su ./Middlewares/wolfssl/wolfcrypt/src/chacha20_poly1305.cyclo ./Middlewares/wolfssl/wolfcrypt/src/chacha20_poly1305.d ./Middlewares/wolfssl/wolfcrypt/src/chacha20_poly1305.o ./Middlewares/wolfssl/wolfcrypt/src/chacha20_poly1305.su ./Middlewares/wolfssl/wolfcrypt/src/cmac.cyclo ./Middlewares/wolfssl/wolfcrypt/src/cmac.d ./Middlewares/wolfssl/wolfcrypt/src/cmac.o ./Middlewares/wolfssl/wolfcrypt/src/cmac.su ./Middlewares/wolfssl/wolfcrypt/src/coding.cyclo ./Middlewares/wolfssl/wolfcrypt/src/coding.d ./Middlewares/wolfssl/wolfcrypt/src/coding.o ./Middlewares/wolfssl/wolfcrypt/src/coding.su ./Middlewares/wolfssl/wolfcrypt/src/compress.cyclo ./Middlewares/wolfssl/wolfcrypt/src/compress.d ./Middlewares/wolfssl/wolfcrypt/src/compress.o ./Middlewares/wolfssl/wolfcrypt/src/compress.su ./Middlewares/wolfssl/wolfcrypt/src/cpuid.cyclo ./Middlewares/wolfssl/wolfcrypt/src/cpuid.d ./Middlewares/wolfssl/wolfcrypt/src/cpuid.o ./Middlewares/wolfssl/wolfcrypt/src/cpuid.su ./Middlewares/wolfssl/wolfcrypt/src/cryptocb.cyclo ./Middlewares/wolfssl/wolfcrypt/src/cryptocb.d ./Middlewares/wolfssl/wolfcrypt/src/cryptocb.o ./Middlewares/wolfssl/wolfcrypt/src/cryptocb.su ./Middlewares/wolfssl/wolfcrypt/src/curve25519.cyclo ./Middlewares/wolfssl/wolfcrypt/src/curve25519.d ./Middlewares/wolfssl/wolfcrypt/src/curve25519.o ./Middlewares/wolfssl/wolfcrypt/src/curve25519.su ./Middlewares/wolfssl/wolfcrypt/src/curve448.cyclo ./Middlewares/wolfssl/wolfcrypt/src/curve448.d ./Middlewares/wolfssl/wolfcrypt/src/curve448.o ./Middlewares/wolfssl/wolfcrypt/src/curve448.su ./Middlewares/wolfssl/wolfcrypt/src/des3.cyclo ./Middlewares/wolfssl/wolfcrypt/src/des3.d ./Middlewares/wolfssl/wolfcrypt/src/des3.o ./Middlewares/wolfssl/wolfcrypt/src/des3.su ./Middlewares/wolfssl/wolfcrypt/src/dh.cyclo ./Middlewares/wolfssl/wolfcrypt/src/dh.d ./Middlewares/wolfssl/wolfcrypt/src/dh.o ./Middlewares/wolfssl/wolfcrypt/src/dh.su ./Middlewares/wolfssl/wolfcrypt/src/dilithium.cyclo ./Middlewares/wolfssl/wolfcrypt/src/dilithium.d ./Middlewares/wolfssl/wolfcrypt/src/dilithium.o ./Middlewares/wolfssl/wolfcrypt/src/dilithium.su ./Middlewares/wolfssl/wolfcrypt/src/dsa.cyclo ./Middlewares/wolfssl/wolfcrypt/src/dsa.d ./Middlewares/wolfssl/wolfcrypt/src/dsa.o ./Middlewares/wolfssl/wolfcrypt/src/dsa.su ./Middlewares/wolfssl/wolfcrypt/src/ecc.cyclo ./Middlewares/wolfssl/wolfcrypt/src/ecc.d ./Middlewares/wolfssl/wolfcrypt/src/ecc.o ./Middlewares/wolfssl/wolfcrypt/src/ecc.su ./Middlewares/wolfssl/wolfcrypt/src/ecc_fp.cyclo ./Middlewares/wolfssl/wolfcrypt/src/ecc_fp.d ./Middlewares/wolfssl/wolfcrypt/src/ecc_fp.o ./Middlewares/wolfssl/wolfcrypt/src/ecc_fp.su ./Middlewares/wolfssl/wolfcrypt/src/eccsi.cyclo ./Middlewares/wolfssl/wolfcrypt/src/eccsi.d ./Middlewares/wolfssl/wolfcrypt/src/eccsi.o ./Middlewares/wolfssl/wolfcrypt/src/eccsi.su ./Middlewares/wolfssl/wolfcrypt/src/ed25519.cyclo ./Middlewares/wolfssl/wolfcrypt/src/ed25519.d ./Middlewares/wolfssl/wolfcrypt/src/ed25519.o ./Middlewares/wolfssl/wolfcrypt/src/ed25519.su ./Middlewares/wolfssl/wolfcrypt/src/ed448.cyclo ./Middlewares/wolfssl/wolfcrypt/src/ed448.d ./Middlewares/wolfssl/wolfcrypt/src/ed448.o ./Middlewares/wolfssl/wolfcrypt/src/ed448.su ./Middlewares/wolfssl/wolfcrypt/src/error.cyclo ./Middlewares/wolfssl/wolfcrypt/src/error.d ./Middlewares/wolfssl/wolfcrypt/src/error.o ./Middlewares/wolfssl/wolfcrypt/src/error.su ./Middlewares/wolfssl/wolfcrypt/src/evp.cyclo ./Middlewares/wolfssl/wolfcrypt/src/evp.d ./Middlewares/wolfssl/wolfcrypt/src/evp.o ./Middlewares/wolfssl/wolfcrypt/src/evp.su ./Middlewares/wolfssl/wolfcrypt/src/ext_lms.cyclo ./Middlewares/wolfssl/wolfcrypt/src/ext_lms.d ./Middlewares/wolfssl/wolfcrypt/src/ext_lms.o ./Middlewares/wolfssl/wolfcrypt/src/ext_lms.su ./Middlewares/wolfssl/wolfcrypt/src/ext_mlkem.cyclo ./Middlewares/wolfssl/wolfcrypt/src/ext_mlkem.d ./Middlewares/wolfssl/wolfcrypt/src/ext_mlkem.o ./Middlewares/wolfssl/wolfcrypt/src/ext_mlkem.su ./Middlewares/wolfssl/wolfcrypt/src/ext_xmss.cyclo ./Middlewares/wolfssl/wolfcrypt/src/ext_xmss.d ./Middlewares/wolfssl/wolfcrypt/src/ext_xmss.o ./Middlewares/wolfssl/wolfcrypt/src/ext_xmss.su ./Middlewares/wolfssl/wolfcrypt/src/falcon.cyclo
	-$(RM) ./Middlewares/wolfssl/wolfcrypt/src/falcon.d ./Middlewares/wolfssl/wolfcrypt/src/falcon.o ./Middlewares/wolfssl/wolfcrypt/src/falcon.su ./Middlewares/wolfssl/wolfcrypt/src/fe_448.cyclo ./Middlewares/wolfssl/wolfcrypt/src/fe_448.d ./Middlewares/wolfssl/wolfcrypt/src/fe_448.o ./Middlewares/wolfssl/wolfcrypt/src/fe_448.su ./Middlewares/wolfssl/wolfcrypt/src/fe_low_mem.cyclo ./Middlewares/wolfssl/wolfcrypt/src/fe_low_mem.d ./Middlewares/wolfssl/wolfcrypt/src/fe_low_mem.o ./Middlewares/wolfssl/wolfcrypt/src/fe_low_mem.su ./Middlewares/wolfssl/wolfcrypt/src/fe_operations.cyclo ./Middlewares/wolfssl/wolfcrypt/src/fe_operations.d ./Middlewares/wolfssl/wolfcrypt/src/fe_operations.o ./Middlewares/wolfssl/wolfcrypt/src/fe_operations.su ./Middlewares/wolfssl/wolfcrypt/src/fips.cyclo ./Middlewares/wolfssl/wolfcrypt/src/fips.d ./Middlewares/wolfssl/wolfcrypt/src/fips.o ./Middlewares/wolfssl/wolfcrypt/src/fips.su ./Middlewares/wolfssl/wolfcrypt/src/fips_test.cyclo ./Middlewares/wolfssl/wolfcrypt/src/fips_test.d ./Middlewares/wolfssl/wolfcrypt/src/fips_test.o ./Middlewares/wolfssl/wolfcrypt/src/fips_test.su ./Middlewares/wolfssl/wolfcrypt/src/ge_448.cyclo ./Middlewares/wolfssl/wolfcrypt/src/ge_448.d ./Middlewares/wolfssl/wolfcrypt/src/ge_448.o ./Middlewares/wolfssl/wolfcrypt/src/ge_448.su ./Middlewares/wolfssl/wolfcrypt/src/ge_low_mem.cyclo ./Middlewares/wolfssl/wolfcrypt/src/ge_low_mem.d ./Middlewares/wolfssl/wolfcrypt/src/ge_low_mem.o ./Middlewares/wolfssl/wolfcrypt/src/ge_low_mem.su ./Middlewares/wolfssl/wolfcrypt/src/ge_operations.cyclo ./Middlewares/wolfssl/wolfcrypt/src/ge_operations.d ./Middlewares/wolfssl/wolfcrypt/src/ge_operations.o ./Middlewares/wolfssl/wolfcrypt/src/ge_operations.su ./Middlewares/wolfssl/wolfcrypt/src/hash.cyclo ./Middlewares/wolfssl/wolfcrypt/src/hash.d ./Middlewares/wolfssl/wolfcrypt/src/hash.o ./Middlewares/wolfssl/wolfcrypt/src/hash.su ./Middlewares/wolfssl/wolfcrypt/src/hmac.cyclo ./Middlewares/wolfssl/wolfcrypt/src/hmac.d ./Middlewares/wolfssl/wolfcrypt/src/hmac.o ./Middlewares/wolfssl/wolfcrypt/src/hmac.su ./Middlewares/wolfssl/wolfcrypt/src/hpke.cyclo ./Middlewares/wolfssl/wolfcrypt/src/hpke.d ./Middlewares/wolfssl/wolfcrypt/src/hpke.o ./Middlewares/wolfssl/wolfcrypt/src/hpke.su ./Middlewares/wolfssl/wolfcrypt/src/integer.cyclo ./Middlewares/wolfssl/wolfcrypt/src/integer.d ./Middlewares/wolfssl/wolfcrypt/src/integer.o ./Middlewares/wolfssl/wolfcrypt/src/integer.su ./Middlewares/wolfssl/wolfcrypt/src/kdf.cyclo ./Middlewares/wolfssl/wolfcrypt/src/kdf.d ./Middlewares/wolfssl/wolfcrypt/src/kdf.o ./Middlewares/wolfssl/wolfcrypt/src/kdf.su ./Middlewares/wolfssl/wolfcrypt/src/logging.cyclo ./Middlewares/wolfssl/wolfcrypt/src/logging.d ./Middlewares/wolfssl/wolfcrypt/src/logging.o ./Middlewares/wolfssl/wolfcrypt/src/logging.su ./Middlewares/wolfssl/wolfcrypt/src/md2.cyclo ./Middlewares/wolfssl/wolfcrypt/src/md2.d ./Middlewares/wolfssl/wolfcrypt/src/md2.o ./Middlewares/wolfssl/wolfcrypt/src/md2.su ./Middlewares/wolfssl/wolfcrypt/src/md4.cyclo ./Middlewares/wolfssl/wolfcrypt/src/md4.d ./Middlewares/wolfssl/wolfcrypt/src/md4.o ./Middlewares/wolfssl/wolfcrypt/src/md4.su ./Middlewares/wolfssl/wolfcrypt/src/md5.cyclo ./Middlewares/wolfssl/wolfcrypt/src/md5.d ./Middlewares/wolfssl/wolfcrypt/src/md5.o ./Middlewares/wolfssl/wolfcrypt/src/md5.su ./Middlewares/wolfssl/wolfcrypt/src/memory.cyclo ./Middlewares/wolfssl/wolfcrypt/src/memory.d ./Middlewares/wolfssl/wolfcrypt/src/memory.o ./Middlewares/wolfssl/wolfcrypt/src/memory.su ./Middlewares/wolfssl/wolfcrypt/src/misc.cyclo ./Middlewares/wolfssl/wolfcrypt/src/misc.d ./Middlewares/wolfssl/wolfcrypt/src/misc.o ./Middlewares/wolfssl/wolfcrypt/src/misc.su ./Middlewares/wolfssl/wolfcrypt/src/pkcs12.cyclo ./Middlewares/wolfssl/wolfcrypt/src/pkcs12.d ./Middlewares/wolfssl/wolfcrypt/src/pkcs12.o ./Middlewares/wolfssl/wolfcrypt/src/pkcs12.su ./Middlewares/wolfssl/wolfcrypt/src/pkcs7.cyclo ./Middlewares/wolfssl/wolfcrypt/src/pkcs7.d ./Middlewares/wolfssl/wolfcrypt/src/pkcs7.o ./Middlewares/wolfssl/wolfcrypt/src/pkcs7.su ./Middlewares/wolfssl/wolfcrypt/src/poly1305.cyclo ./Middlewares/wolfssl/wolfcrypt/src/poly1305.d ./Middlewares/wolfssl/wolfcrypt/src/poly1305.o ./Middlewares/wolfssl/wolfcrypt/src/poly1305.su ./Middlewares/wolfssl/wolfcrypt/src/pwdbased.cyclo ./Middlewares/wolfssl/wolfcrypt/src/pwdbased.d ./Middlewares/wolfssl/wolfcrypt/src/pwdbased.o ./Middlewares/wolfssl/wolfcrypt/src/pwdbased.su ./Middlewares/wolfssl/wolfcrypt/src/random.cyclo ./Middlewares/wolfssl/wolfcrypt/src/random.d ./Middlewares/wolfssl/wolfcrypt/src/random.o ./Middlewares/wolfssl/wolfcrypt/src/random.su ./Middlewares/wolfssl/wolfcrypt/src/rc2.cyclo ./Middlewares/wolfssl/wolfcrypt/src/rc2.d ./Middlewares/wolfssl/wolfcrypt/src/rc2.o ./Middlewares/wolfssl/wolfcrypt/src/rc2.su ./Middlewares/wolfssl/wolfcrypt/src/ripemd.cyclo ./Middlewares/wolfssl/wolfcrypt/src/ripemd.d ./Middlewares/wolfssl/wolfcrypt/src/ripemd.o ./Middlewares/wolfssl/wolfcrypt/src/ripemd.su ./Middlewares/wolfssl/wolfcrypt/src/rsa.cyclo ./Middlewares/wolfssl/wolfcrypt/src/rsa.d ./Middlewares/wolfssl/wolfcrypt/src/rsa.o ./Middlewares/wolfssl/wolfcrypt/src/rsa.su ./Middlewares/wolfssl/wolfcrypt/src/sakke.cyclo ./Middlewares/wolfssl/wolfcrypt/src/sakke.d ./Middlewares/wolfssl/wolfcrypt/src/sakke.o ./Middlewares/wolfssl/wolfcrypt/src/sakke.su ./Middlewares/wolfssl/wolfcrypt/src/selftest.cyclo ./Middlewares/wolfssl/wolfcrypt/src/selftest.d ./Middlewares/wolfssl/wolfcrypt/src/selftest.o ./Middlewares/wolfssl/wolfcrypt/src/selftest.su ./Middlewares/wolfssl/wolfcrypt/src/sha.cyclo ./Middlewares/wolfssl/wolfcrypt/src/sha.d ./Middlewares/wolfssl/wolfcrypt/src/sha.o ./Middlewares/wolfssl/wolfcrypt/src/sha.su ./Middlewares/wolfssl/wolfcrypt/src/sha256.cyclo ./Middlewares/wolfssl/wolfcrypt/src/sha256.d ./Middlewares/wolfssl/wolfcrypt/src/sha256.o ./Middlewares/wolfssl/wolfcrypt/src/sha256.su ./Middlewares/wolfssl/wolfcrypt/src/sha3.cyclo ./Middlewares/wolfssl/wolfcrypt/src/sha3.d
	-$(RM) ./Middlewares/wolfssl/wolfcrypt/src/sha3.o ./Middlewares/wolfssl/wolfcrypt/src/sha3.su ./Middlewares/wolfssl/wolfcrypt/src/sha512.cyclo ./Middlewares/wolfssl/wolfcrypt/src/sha512.d ./Middlewares/wolfssl/wolfcrypt/src/sha512.o ./Middlewares/wolfssl/wolfcrypt/src/sha512.su ./Middlewares/wolfssl/wolfcrypt/src/signature.cyclo ./Middlewares/wolfssl/wolfcrypt/src/signature.d ./Middlewares/wolfssl/wolfcrypt/src/signature.o ./Middlewares/wolfssl/wolfcrypt/src/signature.su ./Middlewares/wolfssl/wolfcrypt/src/siphash.cyclo ./Middlewares/wolfssl/wolfcrypt/src/siphash.d ./Middlewares/wolfssl/wolfcrypt/src/siphash.o ./Middlewares/wolfssl/wolfcrypt/src/siphash.su ./Middlewares/wolfssl/wolfcrypt/src/sm2.cyclo ./Middlewares/wolfssl/wolfcrypt/src/sm2.d ./Middlewares/wolfssl/wolfcrypt/src/sm2.o ./Middlewares/wolfssl/wolfcrypt/src/sm2.su ./Middlewares/wolfssl/wolfcrypt/src/sm3.cyclo ./Middlewares/wolfssl/wolfcrypt/src/sm3.d ./Middlewares/wolfssl/wolfcrypt/src/sm3.o ./Middlewares/wolfssl/wolfcrypt/src/sm3.su ./Middlewares/wolfssl/wolfcrypt/src/sm4.cyclo ./Middlewares/wolfssl/wolfcrypt/src/sm4.d ./Middlewares/wolfssl/wolfcrypt/src/sm4.o ./Middlewares/wolfssl/wolfcrypt/src/sm4.su ./Middlewares/wolfssl/wolfcrypt/src/sp_arm32.cyclo ./Middlewares/wolfssl/wolfcrypt/src/sp_arm32.d ./Middlewares/wolfssl/wolfcrypt/src/sp_arm32.o ./Middlewares/wolfssl/wolfcrypt/src/sp_arm32.su ./Middlewares/wolfssl/wolfcrypt/src/sp_arm64.cyclo ./Middlewares/wolfssl/wolfcrypt/src/sp_arm64.d ./Middlewares/wolfssl/wolfcrypt/src/sp_arm64.o ./Middlewares/wolfssl/wolfcrypt/src/sp_arm64.su ./Middlewares/wolfssl/wolfcrypt/src/sp_armthumb.cyclo ./Middlewares/wolfssl/wolfcrypt/src/sp_armthumb.d ./Middlewares/wolfssl/wolfcrypt/src/sp_armthumb.o ./Middlewares/wolfssl/wolfcrypt/src/sp_armthumb.su ./Middlewares/wolfssl/wolfcrypt/src/sp_c32.cyclo ./Middlewares/wolfssl/wolfcrypt/src/sp_c32.d ./Middlewares/wolfssl/wolfcrypt/src/sp_c32.o ./Middlewares/wolfssl/wolfcrypt/src/sp_c32.su ./Middlewares/wolfssl/wolfcrypt/src/sp_c64.cyclo ./Middlewares/wolfssl/wolfcrypt/src/sp_c64.d ./Middlewares/wolfssl/wolfcrypt/src/sp_c64.o ./Middlewares/wolfssl/wolfcrypt/src/sp_c64.su ./Middlewares/wolfssl/wolfcrypt/src/sp_cortexm.cyclo ./Middlewares/wolfssl/wolfcrypt/src/sp_cortexm.d ./Middlewares/wolfssl/wolfcrypt/src/sp_cortexm.o ./Middlewares/wolfssl/wolfcrypt/src/sp_cortexm.su ./Middlewares/wolfssl/wolfcrypt/src/sp_dsp32.cyclo ./Middlewares/wolfssl/wolfcrypt/src/sp_dsp32.d ./Middlewares/wolfssl/wolfcrypt/src/sp_dsp32.o ./Middlewares/wolfssl/wolfcrypt/src/sp_dsp32.su ./Middlewares/wolfssl/wolfcrypt/src/sp_int.cyclo ./Middlewares/wolfssl/wolfcrypt/src/sp_int.d ./Middlewares/wolfssl/wolfcrypt/src/sp_int.o ./Middlewares/wolfssl/wolfcrypt/src/sp_int.su ./Middlewares/wolfssl/wolfcrypt/src/sp_sm2_arm32.cyclo ./Middlewares/wolfssl/wolfcrypt/src/sp_sm2_arm32.d ./Middlewares/wolfssl/wolfcrypt/src/sp_sm2_arm32.o ./Middlewares/wolfssl/wolfcrypt/src/sp_sm2_arm32.su ./Middlewares/wolfssl/wolfcrypt/src/sp_sm2_arm64.cyclo ./Middlewares/wolfssl/wolfcrypt/src/sp_sm2_arm64.d ./Middlewares/wolfssl/wolfcrypt/src/sp_sm2_arm64.o ./Middlewares/wolfssl/wolfcrypt/src/sp_sm2_arm64.su ./Middlewares/wolfssl/wolfcrypt/src/sp_sm2_armthumb.cyclo ./Middlewares/wolfssl/wolfcrypt/src/sp_sm2_armthumb.d ./Middlewares/wolfssl/wolfcrypt/src/sp_sm2_armthumb.o ./Middlewares/wolfssl/wolfcrypt/src/sp_sm2_armthumb.su ./Middlewares/wolfssl/wolfcrypt/src/sp_sm2_c32.cyclo ./Middlewares/wolfssl/wolfcrypt/src/sp_sm2_c32.d ./Middlewares/wolfssl/wolfcrypt/src/sp_sm2_c32.o ./Middlewares/wolfssl/wolfcrypt/src/sp_sm2_c32.su ./Middlewares/wolfssl/wolfcrypt/src/sp_sm2_c64.cyclo ./Middlewares/wolfssl/wolfcrypt/src/sp_sm2_c64.d ./Middlewares/wolfssl/wolfcrypt/src/sp_sm2_c64.o ./Middlewares/wolfssl/wolfcrypt/src/sp_sm2_c64.su ./Middlewares/wolfssl/wolfcrypt/src/sp_sm2_cortexm.cyclo ./Middlewares/wolfssl/wolfcrypt/src/sp_sm2_cortexm.d ./Middlewares/wolfssl/wolfcrypt/src/sp_sm2_cortexm.o ./Middlewares/wolfssl/wolfcrypt/src/sp_sm2_cortexm.su ./Middlewares/wolfssl/wolfcrypt/src/sp_sm2_x86_64.cyclo ./Middlewares/wolfssl/wolfcrypt/src/sp_sm2_x86_64.d ./Middlewares/wolfssl/wolfcrypt/src/sp_sm2_x86_64.o ./Middlewares/wolfssl/wolfcrypt/src/sp_sm2_x86_64.su ./Middlewares/wolfssl/wolfcrypt/src/sp_x86_64.cyclo ./Middlewares/wolfssl/wolfcrypt/src/sp_x86_64.d ./Middlewares/wolfssl/wolfcrypt/src/sp_x86_64.o ./Middlewares/wolfssl/wolfcrypt/src/sp_x86_64.su ./Middlewares/wolfssl/wolfcrypt/src/sphincs.cyclo ./Middlewares/wolfssl/wolfcrypt/src/sphincs.d ./Middlewares/wolfssl/wolfcrypt/src/sphincs.o ./Middlewares/wolfssl/wolfcrypt/src/sphincs.su ./Middlewares/wolfssl/wolfcrypt/src/srp.cyclo ./Middlewares/wolfssl/wolfcrypt/src/srp.d ./Middlewares/wolfssl/wolfcrypt/src/srp.o ./Middlewares/wolfssl/wolfcrypt/src/srp.su ./Middlewares/wolfssl/wolfcrypt/src/tfm.cyclo ./Middlewares/wolfssl/wolfcrypt/src/tfm.d ./Middlewares/wolfssl/wolfcrypt/src/tfm.o ./Middlewares/wolfssl/wolfcrypt/src/tfm.su ./Middlewares/wolfssl/wolfcrypt/src/wc_dsp.cyclo ./Middlewares/wolfssl/wolfcrypt/src/wc_dsp.d ./Middlewares/wolfssl/wolfcrypt/src/wc_dsp.o ./Middlewares/wolfssl/wolfcrypt/src/wc_dsp.su ./Middlewares/wolfssl/wolfcrypt/src/wc_encrypt.cyclo ./Middlewares/wolfssl/wolfcrypt/src/wc_encrypt.d ./Middlewares/wolfssl/wolfcrypt/src/wc_encrypt.o ./Middlewares/wolfssl/wolfcrypt/src/wc_encrypt.su ./Middlewares/wolfssl/wolfcrypt/src/wc_lms.cyclo ./Middlewares/wolfssl/wolfcrypt/src/wc_lms.d ./Middlewares/wolfssl/wolfcrypt/src/wc_lms.o ./Middlewares/wolfssl/wolfcrypt/src/wc_lms.su ./Middlewares/wolfssl/wolfcrypt/src/wc_lms_impl.cyclo ./Middlewares/wolfssl/wolfcrypt/src/wc_lms_impl.d ./Middlewares/wolfssl/wolfcrypt/src/wc_lms_impl.o ./Middlewares/wolfssl/wolfcrypt/src/wc_lms_impl.su ./Middlewares/wolfssl/wolfcrypt/src/wc_mlkem.cyclo ./Middlewares/wolfssl/wolfcrypt/src/wc_mlkem.d ./Middlewares/wolfssl/wolfcrypt/src/wc_mlkem.o ./Middlewares/wolfssl/wolfcrypt/src/wc_mlkem.su ./Middlewares/wolfssl/wolfcrypt/src/wc_mlkem_poly.cyclo
	-$(RM) ./Middlewares/wolfssl/wolfcrypt/src/wc_mlkem_poly.d ./Middlewares/wolfssl/wolfcrypt/src/wc_mlkem_poly.o ./Middlewares/wolfssl/wolfcrypt/src/wc_mlkem_poly.su ./Middlewares/wolfssl/wolfcrypt/src/wc_pkcs11.cyclo ./Middlewares/wolfssl/wolfcrypt/src/wc_pkcs11.d ./Middlewares/wolfssl/wolfcrypt/src/wc_pkcs11.o ./Middlewares/wolfssl/wolfcrypt/src/wc_pkcs11.su ./Middlewares/wolfssl/wolfcrypt/src/wc_port.cyclo ./Middlewares/wolfssl/wolfcrypt/src/wc_port.d ./Middlewares/wolfssl/wolfcrypt/src/wc_port.o ./Middlewares/wolfssl/wolfcrypt/src/wc_port.su ./Middlewares/wolfssl/wolfcrypt/src/wc_xmss.cyclo ./Middlewares/wolfssl/wolfcrypt/src/wc_xmss.d ./Middlewares/wolfssl/wolfcrypt/src/wc_xmss.o ./Middlewares/wolfssl/wolfcrypt/src/wc_xmss.su ./Middlewares/wolfssl/wolfcrypt/src/wc_xmss_impl.cyclo ./Middlewares/wolfssl/wolfcrypt/src/wc_xmss_impl.d ./Middlewares/wolfssl/wolfcrypt/src/wc_xmss_impl.o ./Middlewares/wolfssl/wolfcrypt/src/wc_xmss_impl.su ./Middlewares/wolfssl/wolfcrypt/src/wolfcrypt_first.cyclo ./Middlewares/wolfssl/wolfcrypt/src/wolfcrypt_first.d ./Middlewares/wolfssl/wolfcrypt/src/wolfcrypt_first.o ./Middlewares/wolfssl/wolfcrypt/src/wolfcrypt_first.su ./Middlewares/wolfssl/wolfcrypt/src/wolfcrypt_last.cyclo ./Middlewares/wolfssl/wolfcrypt/src/wolfcrypt_last.d ./Middlewares/wolfssl/wolfcrypt/src/wolfcrypt_last.o ./Middlewares/wolfssl/wolfcrypt/src/wolfcrypt_last.su ./Middlewares/wolfssl/wolfcrypt/src/wolfevent.cyclo ./Middlewares/wolfssl/wolfcrypt/src/wolfevent.d ./Middlewares/wolfssl/wolfcrypt/src/wolfevent.o ./Middlewares/wolfssl/wolfcrypt/src/wolfevent.su ./Middlewares/wolfssl/wolfcrypt/src/wolfmath.cyclo ./Middlewares/wolfssl/wolfcrypt/src/wolfmath.d ./Middlewares/wolfssl/wolfcrypt/src/wolfmath.o ./Middlewares/wolfssl/wolfcrypt/src/wolfmath.su

.PHONY: clean-Middlewares-2f-wolfssl-2f-wolfcrypt-2f-src

